# Generated by Django 2.2.2 on 2019-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
