# Generated by Django 2.2.2 on 2019-06-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_coursepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepost',
            old_name='topic',
            new_name='module',
        ),
    ]
