# Generated by Django 2.2.2 on 2019-06-20 15:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_aj101fall19post_coauthors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps324fall19post',
            name='coauthors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PS User10', 'PS User10'), ('PS User20', 'PS User20'), ('PS User4', 'PS User4')], default='', max_length=28),
        ),
    ]
