# Generated by Django 2.2.2 on 2019-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='NA', max_length=254),
        ),
    ]
