# Generated by Django 2.2.2 on 2019-06-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190612_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.CharField(choices=[('AJ 101_FALL2019', 'AJ101 Fall 2019'), ('PS324 Fall 2019', 'PS324 Fall 2019')], default='', max_length=255),
        ),
    ]
